# Generated by Django 3.2.19 on 2023-12-13 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_iD', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('revenue', models.FloatField()),
                ('net_income', models.FloatField()),
                ('earnings_per_share', models.FloatField()),
                ('current_ratio', models.FloatField()),
                ('debt_to_equity_ratio', models.FloatField()),
                ('return_on_quality', models.FloatField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_app.company')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_app.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_app.expensecategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_app.company'),
        ),
    ]
