# Generated by Django 3.2.19 on 2023-12-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdata',
            name='earnings_per_share',
        ),
        migrations.RemoveField(
            model_name='financialdata',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='financialdata',
            name='return_on_quality',
        ),
        migrations.AddField(
            model_name='financialdata',
            name='total_expense',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
