# Generated by Django 3.2.19 on 2023-12-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0002_auto_20231213_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='total_expense',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
