# Generated by Django 3.2.19 on 2023-12-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0003_expense_total_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='total_expense',
        ),
    ]
