# Generated by Django 3.2.19 on 2023-12-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0004_remove_expense_total_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdata',
            name='total_sale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='total_expense',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
