# Generated by Django 3.2.19 on 2023-12-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0005_auto_20231213_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdata',
            name='net_income',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
